services:
  postgres:
    image: postgres:16-alpine
    container_name: nexo-postgres
    restart: always

    environment:
      POSTGRES_USER: ${POSTGRES_USER:-nexo}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-nexo_password}
      POSTGRES_DB: ${POSTGRES_DB:-nexo_db}

    ports:
      - "${DB_PORT:-5435}:5432"

    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: